services:
     mafiascum.automodServer.listener:
        class: mafiascum\automodServer\event\main_listener
        arguments:
            - '@controller.helper'
            - '@template'
            - '@request'
            - '@dbal.conn'
            - '@user'
            - '@user_loader'
            - '@language'
            - '@auth'
            - '%core.table_prefix%'
        tags:
            - { name: event.listener }
     mafiascum.gameApi.gameApiController:
        class: mafiascum\automodServer\controller\GameApi
        arguments:
            - '@controller.helper'
            - '@template'
            - '@request'
            - '@dbal.conn'
            - '@user'
            - '@user_loader'
            - '@language'
            - '@auth'
